etsycookies = [
    {
        "domain": ".etsy.com",
        "expirationDate": 1559835238,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_fbp",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "fb.1.1552059189013.1769836739"
    },
    {
        "domain": ".etsy.com",
        "expirationDate": 1559835185,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "1.1.2072790042.1552059185"
    },
    {
        "domain": ".etsy.com",
        "expirationDate": 1586245938.132742,
        "hostOnly": False,
        "httpOnly": False,
        "name": "fve",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "1552059179.0"
    },
    {
        "domain": ".etsy.com",
        "expirationDate": 1552059294.112093,
        "hostOnly": False,
        "httpOnly": True,
        "name": "gtm_deferred",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "%5B%5D"
    },
    {
        "domain": ".etsy.com",
        "hostOnly": False,
        "httpOnly": False,
        "name": "last_browse_page",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": False,
        "session": True,
        "storeId": "0",
        "value": "https%3A%2F%2Fwww.etsy.com%2F"
    },
    {
        "domain": ".etsy.com",
        "expirationDate": 1583595180.518957,
        "hostOnly": False,
        "httpOnly": False,
        "name": "uaid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "Ax3CV7sFAxe1VF35Gxo3yJGQjk1jZACCmKZubRhdrVSamJmiZKXkWWJk6mxU5VXpWlZanmSUVplZEeHimGJc6JXnrFTLAAA."
    },
    {
        "domain": ".etsy.com",
        "expirationDate": 1583595232.774076,
        "hostOnly": False,
        "httpOnly": False,
        "name": "user_prefs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "ZQYWEmoWkS1XaC9r7e-M_GBwQoNjZACCmKZubSidEK0UGuyipKOUnpiTk1pUCWSl5umGBgNpEJFXmpOjYwShsBCxDAA."
    },
    {
        "domain": "www.etsy.com",
        "expirationDate": 1583595234.806508,
        "hostOnly": True,
        "httpOnly": False,
        "name": "ua",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "531227642bc86f3b5fd7103a0c0b4fd6"
    }
]
